### ISSUE TITLE
Skip antialiasing for 45° lines too…

### ISSUE THREAD

**Issue by mwarrenus** [gregoiresage/pebble-antialiasing-lib#2]
In `graphics_draw_line_antialiased`, 45° lines can skip antialiasing too, correct?  
    …
    if(p0.x == p1.x || p0.y == p1.y **|| p0.x-p1.x == p0.y-p1.y**){
        graphics_draw_line(ctx, p0, p1);
    }
   …

**Comment by gregoiresage** [comment]
Honestly, I didn't test the difference between normal and antialiased lines for 45° lines. I guess you are right, I will update the code asap

**Comment by mwarrenus** [comment]
Whoops! my suggested code has a bug; it should use **abs(p0.x - p1.x) == abs(p0.y - p1.y)**
